export const REQUEST_POST_COMMENTS = 'REQUEST_POST_COMMENTS';
export const RECEIVE_POST_COMMENTS = 'RECEIVE_POST_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REQUEST_COMMENT_DETAILS = 'REQUEST_COMMENT_DETAILS';
export const RECEIVE_COMMENT_DETAILS = 'RECEIVE_COMMENT_DETAILS';
export const VOTE_COMMENT = 'VOTE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';