export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const ADD_POST = 'ADD_POST';
export const REQUEST_POST_DETAILS = 'REQUEST_POST_DETAILS';
export const RECEIVE_POST_DETAILS = 'RECEIVE_POST_DETAILS';
export const VOTE_POST = 'VOTE_POST';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';